Transform: AWS::Serverless-2016-10-31
Resources:
  SnowflakeCreateUserLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: versent-snowflake-create-user
      CodeUri: src/Function
      Handler: lambda_function.handler
      Runtime: python3.11
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          authenticator: SNOWFLAKE_JWT
          bucket: versent-lambda-layers
          database: USERDB_JEMIMAVILLANUEVA
          object_key: rsa_key_dev.p8
          region: ap-southeast-2
          schema: PUBLIC
          snowflake_account: versent_partner
          user: jemima.villanueva@versent.com.sg
          warehouse: DEMO_WH
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${Function}
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Layer ${ResourceName}
        - ResourceName: Layer
      ContentUri: src/Layer
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11